// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	api_relation "github.com/YANGJUNYAN0715/douyin/tree/guo/cmd/api/biz/router/api_relation"
	api_user "github.com/YANGJUNYAN0715/douyin/tree/guo/cmd/api/biz/router/api_user"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	api_relation.Register(r)

	api_user.Register(r)


}
