# init_api:
# 	hz new -mod "douyin" -idl ../../idl/api.proto

# update_api:
# 	hz update -mod "douyin" -idl ../../idl/api.proto

init_api:
	hz new -mod "douyin" -idl ../../idl/api.thrift

update_api:
	hz update  -idl ../../idl/api.thrift