// Code generated by hertz generator.

package api

import (
	"context"

	api "github.com/YANGJUNYAN0715/douyin/tree/guo/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// LoginUser .
// @router /user/login [POST]
func LoginUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.LoginUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.LoginUserResponse)

	c.JSON(consts.StatusOK, resp)
}

// RegisterUser .
// @router /user/register [POST]
func RegisterUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RegisterUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.RegisterUserResponse)

	c.JSON(consts.StatusOK, resp)
}
