// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/YANGJUNYAN0715/douyin/tree/zhao/cmd/api/biz/model/api"
	"github.com/YANGJUNYAN0715/douyin/tree/zhao/cmd/api/biz/mw"
	"github.com/YANGJUNYAN0715/douyin/tree/zhao/cmd/api/biz/rpc"
	"github.com/YANGJUNYAN0715/douyin/tree/zhao/kitex_gen/user"
	// "github.com/YANGJUNYAN0715/douyin/tree/zhao/pkg/consts"
	"github.com/YANGJUNYAN0715/douyin/tree/zhao/pkg/errno"
	"github.com/cloudwego/hertz/pkg/app"
	// "github.com/cloudwego/hertz/pkg/common/utils"
)

// Register .
// @router /douyin/user/register/ [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DouyinUserRegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}

	err = rpc.Register(context.Background(),&user.DouyinUserRegisterRequest{
		Username: req.Username,
		Password: req.Password,
	})
	if err != nil{
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	SendResponse(c, errno.Success, nil)
}

// Login .
// @router /douyin/user/login/ [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	mw.JwtMiddleware.LoginHandler(ctx, c)
}
